package ru.andremoniy.jcocoa;

import ru.andremoniy.jcocoa.*;
import ns.NSMutableDictionary;
import static ns.NSMutableDictionary.*;
import ns.INSMutableDictionary;
import static ns.INSMutableDictionary.*;
import ns.NSArray;
import static ns.NSArray.*;
import ns.INSArray;
import static ns.INSArray.*;
import ns.NSDictionary;
import static ns.NSDictionary.*;
import ns.INSDictionary;
import static ns.INSDictionary.*;
import ns.NSData;
import static ns.NSData.*;
import ns.INSData;
import static ns.INSData.*;
import ns.NSPasteboard;
import static ns.NSPasteboard.*;
import ns.INSPasteboard;
import static ns.INSPasteboard.*;
import ns.NSFileWrapper;
import static ns.NSFileWrapper.*;
import ns.INSFileWrapper;
import static ns.INSFileWrapper.*;

import ns.NSObject;

public abstract class INSPasteboard extends NSObject {

	protected NSObject _pboard;
	protected int _gen;
	protected NSObject _owners;
	protected CFIndex _cachedTypeNameChangeCount;
	protected NSObject _cachedTypeNames;
	protected NSMutableDictionary _promiseTypeNamesByIdentifier;
	protected NSObject _support;
	protected NSObject _pasteboardItems;
	protected void _reserved;

	public String name() { return null;
};
	public Integer changeCount() { return null;
};
	public void releaseGlobally() { return ;
};
	public Integer clearContents() { return null;
};
	public Boolean writeObjects(NSArray objects) { return null;
};
	public NSArray readObjectsForClasses(NSArray classArray, NSDictionary options) { return null;
};
	public NSArray pasteboardItems() { return null;
};
	public Integer indexOfPasteboardItem(NSPasteboardItem pasteboardItem) { return null;
};
	public Boolean canReadItemWithDataConformingToTypes(NSArray types) { return null;
};
	public Boolean canReadObjectForClasses(NSArray classArray, NSDictionary options) { return null;
};
	public Integer declareTypes(NSArray newTypes, NSObject newOwner) { return null;
};
	public Integer addTypes(NSArray newTypes, NSObject newOwner) { return null;
};
	public NSArray types() { return null;
};
	public String availableTypeFromArray(NSArray types) { return null;
};
	public Boolean setData(NSData data, String dataType) { return null;
};
	public Boolean setPropertyList(NSObject plist, String dataType) { return null;
};
	public Boolean setString(String string, String dataType) { return null;
};
	public NSData dataForType(String dataType) { return null;
};
	public NSObject propertyListForType(String dataType) { return null;
};
	public String stringForType(String dataType) { return null;
};
	public void pasteboard(NSPasteboard sender, String type) { return ;
};
	public void pasteboardChangedOwner(NSPasteboard sender) { return ;
};
	public void writeToPasteboard(NSPasteboard pasteBoard) { return ;
};
	public Boolean writeFileContents(String filename) { return null;
};
	public String readFileContentsType(String type, String filename) { return null;
};
	public Boolean writeFileWrapper(NSFileWrapper wrapper) { return null;
};
	public NSFileWrapper readFileWrapper() { return null;
};
}
