package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;

public abstract class INSAttributedString {
	public static String NSFontAttributeName;
	public static String NSParagraphStyleAttributeName;
	public static String NSForegroundColorAttributeName;
	public static String NSUnderlineStyleAttributeName;
	public static String NSSuperscriptAttributeName;
	public static String NSBackgroundColorAttributeName;
	public static String NSAttachmentAttributeName;
	public static String NSLigatureAttributeName;
	public static String NSBaselineOffsetAttributeName;
	public static String NSKernAttributeName;
	public static String NSLinkAttributeName;
	public static String NSStrokeWidthAttributeName;
	public static String NSStrokeColorAttributeName;
	public static String NSUnderlineColorAttributeName;
	public static String NSStrikethroughStyleAttributeName;
	public static String NSStrikethroughColorAttributeName;
	public static String NSShadowAttributeName;
	public static String NSObliquenessAttributeName;
	public static String NSExpansionAttributeName;
	public static String NSCursorAttributeName;
	public static String NSToolTipAttributeName;
	public static String NSCharacterShapeAttributeName;
	public static String NSGlyphInfoAttributeName;
	public static String NSWritingDirectionAttributeName;
	public static String NSMarkedClauseSegmentAttributeName;
public static Integer NSUnderlineStyleNone = 0x00;
public static Integer NSUnderlineStyleSingle = 0x01;
public static Integer NSUnderlineStyleThick = 0x02;
public static Integer NSUnderlineStyleDouble = 0x09;
public static Integer NSUnderlinePatternSolid = 0x0000;
public static Integer NSUnderlinePatternDot = 0x0100;
public static Integer NSUnderlinePatternDash = 0x0200;
public static Integer NSUnderlinePatternDashDot = 0x0300;
public static Integer NSUnderlinePatternDashDotDot = 0x0400;
	public static Integer NSUnderlineByWordMask;
	public static String NSSpellingStateAttributeName;
	public static String NSPlainTextDocumentType;
	public static String NSRTFTextDocumentType;
	public static String NSRTFDTextDocumentType;
	public static String NSMacSimpleTextDocumentType;
	public static String NSHTMLTextDocumentType;
	public static String NSDocFormatTextDocumentType;
	public static String NSWordMLTextDocumentType;
	public static String NSWebArchiveTextDocumentType;
	public static String NSOfficeOpenXMLTextDocumentType;
	public static String NSOpenDocumentTextDocumentType;
	public static String NSPaperSizeDocumentAttribute;
	public static String NSLeftMarginDocumentAttribute;
	public static String NSRightMarginDocumentAttribute;
	public static String NSTopMarginDocumentAttribute;
	public static String NSBottomMarginDocumentAttribute;
	public static String NSViewSizeDocumentAttribute;
	public static String NSViewZoomDocumentAttribute;
	public static String NSViewModeDocumentAttribute;
	public static String NSDocumentTypeDocumentAttribute;
	public static String NSReadOnlyDocumentAttribute;
	public static String NSConvertedDocumentAttribute;
	public static String NSCocoaVersionDocumentAttribute;
	public static String NSBackgroundColorDocumentAttribute;
	public static String NSHyphenationFactorDocumentAttribute;
	public static String NSDefaultTabIntervalDocumentAttribute;
	public static String NSCharacterEncodingDocumentAttribute;
	public static String NSFileTypeDocumentAttribute;
	public static String NSTitleDocumentAttribute;
	public static String NSCompanyDocumentAttribute;
	public static String NSCopyrightDocumentAttribute;
	public static String NSSubjectDocumentAttribute;
	public static String NSAuthorDocumentAttribute;
	public static String NSKeywordsDocumentAttribute;
	public static String NSCommentDocumentAttribute;
	public static String NSEditorDocumentAttribute;
	public static String NSCreationTimeDocumentAttribute;
	public static String NSModificationTimeDocumentAttribute;
	public static String NSManagerDocumentAttribute;
	public static String NSCategoryDocumentAttribute;
	public static String NSExcludedElementsDocumentAttribute;
	public static String NSTextEncodingNameDocumentAttribute;
	public static String NSPrefixSpacesDocumentAttribute;
	public static String NSDocumentTypeDocumentOption;
	public static String NSDefaultAttributesDocumentOption;
	public static String NSCharacterEncodingDocumentOption;
	public static String NSTextEncodingNameDocumentOption;
	public static String NSBaseURLDocumentOption;
	public static String NSTimeoutDocumentOption;
	public static String NSWebPreferencesDocumentOption;
	public static String NSWebResourceLoadDelegateDocumentOption;
	public static String NSTextSizeMultiplierDocumentOption;
	public static String NSFileTypeDocumentOption;
public static Integer NSNoUnderlineStyle = 0;
public static Integer NSSingleUnderlineStyle = null;
	public static Integer NSUnderlineStrikethroughMask;
public abstract static class INSMutableAttributedString {
	public Boolean readFromURL(NSURL url, NSDictionary options, NSDictionary dict) { return null;
};
	public void superscriptRange(NSRange range) { return ;
};
	public void subscriptRange(NSRange range) { return ;
};
	public void unscriptRange(NSRange range) { return ;
};
	public void applyFontTraits(NSFontTraitMask traitMask, NSRange range) { return ;
};
	public void setAlignment(NSTextAlignment alignment, NSRange range) { return ;
};
	public void fixAttributesInRange(NSRange range) { return ;
};
	public void fixFontAttributeInRange(NSRange range) { return ;
};
	public void fixParagraphStyleAttributeInRange(NSRange range) { return ;
};
	public void fixAttachmentAttributeInRange(NSRange range) { return ;
};

}
}
