package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSInputManager;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSInputManager.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSInputManager;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSInputManager.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSInputServer;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSInputServer.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;

public abstract class INSInputManager extends NSObject {

	protected NSObject _currentClient;
	protected NSObject _server;
	protected NSObject _bundleObj;
	protected NSObject _keybindings;
	protected String _trueName;
	protected String _connectionName;
	protected String _hostName;
	protected String _procToExec;
	protected String _visibleName;
	protected String _bundleName;
	protected String _language;
	protected NSImage _image;
	protected Integer _flags;
	protected String _keyBindingsName;
	protected Integer _reservedInputManager2;

	public NSInputManager initWithName(String inputServerName, String hostName) { return null;
};
	public String localizedInputManagerName() { return null;
};
	public void markedTextAbandoned(NSObject cli) { return ;
};
	public void markedTextSelectionChanged(NSRange newSel, NSObject cli) { return ;
};
	public Boolean wantsToInterpretAllKeystrokes() { return null;
};
	public String language() { return null;
};
	public NSImage image() { return null;
};
	public NSInputServer server() { return null;
};
	public Boolean wantsToHandleMouseEvents() { return null;
};
	public Boolean handleMouseEvent(NSEvent theMouseEvent) { return null;
};
	public Boolean wantsToDelayTextChangeNotifications() { return null;
};
	public abstract class NSTextInput {
	public void insertText(NSObject aString) { return ;
};
	public void doCommandBySelector(SEL aSelector) { return ;
};
	public void setMarkedText(NSObject aString, NSRange selRange) { return ;
};
	public void unmarkText() { return ;
};
	public Boolean hasMarkedText() { return null;
};
	public Integer conversationIdentifier() { return null;
};
	public NSAttributedString attributedSubstringFromRange(NSRange theRange) { return null;
};
	public NSRange markedRange() { return null;
};
	public NSRange selectedRange() { return null;
};
	public NSRect firstRectForCharacterRange(NSRange theRange) { return null;
};
	public Integer characterIndexForPoint(NSPoint thePoint) { return null;
};
	public NSArray validAttributesForMarkedText() { return null;
};
	
}
}
