package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;

public abstract class INSPopUpButton extends NSButton {
	public NSObject initWithFrame(NSRect buttonFrame, Boolean flag) { return null;
};
	public void setMenu(NSMenu menu) { return ;
};
	public NSMenu menu() { return null;
};
	public void setPullsDown(Boolean flag) { return ;
};
	public Boolean pullsDown() { return null;
};
	public void setAutoenablesItems(Boolean flag) { return ;
};
	public Boolean autoenablesItems() { return null;
};
	public void setPreferredEdge(NSRectEdge edge) { return ;
};
	public NSRectEdge preferredEdge() { return null;
};
	public void addItemWithTitle(String title) { return ;
};
	public void addItemsWithTitles(NSArray itemTitles) { return ;
};
	public void insertItemWithTitle(String title, Integer index) { return ;
};
	public void removeItemWithTitle(String title) { return ;
};
	public void removeItemAtIndex(Integer index) { return ;
};
	public void removeAllItems() { return ;
};
	public NSArray itemArray() { return null;
};
	public Integer numberOfItems() { return null;
};
	public Integer indexOfItem(NSMenuItem item) { return null;
};
	public Integer indexOfItemWithTitle(String title) { return null;
};
	public Integer indexOfItemWithTag(Integer tag) { return null;
};
	public Integer indexOfItemWithRepresentedObject(NSObject obj) { return null;
};
	public Integer indexOfItemWithTarget(NSObject target, SEL actionSelector) { return null;
};
	public NSMenuItem itemAtIndex(Integer index) { return null;
};
	public NSMenuItem itemWithTitle(String title) { return null;
};
	public NSMenuItem lastItem() { return null;
};
	public void selectItem(NSMenuItem item) { return ;
};
	public void selectItemAtIndex(Integer index) { return ;
};
	public void selectItemWithTitle(String title) { return ;
};
	public void setTitle(String aString) { return ;
};
	public NSMenuItem selectedItem() { return null;
};
	public Integer indexOfSelectedItem() { return null;
};
	public void synchronizeTitleAndSelectedItem() { return ;
};
	public String itemTitleAtIndex(Integer index) { return null;
};
	public NSArray itemTitles() { return null;
};
	public String titleOfSelectedItem() { return null;
};
	public static String NSPopUpButtonWillPopUpNotification;
}
