package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;

public abstract class INSTabViewItem extends NSObject {

	protected NSObject _identifier;
	protected String _label;
	protected NSView _view;
	protected NSView _initialFirstResponder;
	protected NSColor _color;
	protected NSTabView _tabView;
	protected NSTabState _tabState;
	protected NSView _lastKeyView;


	protected NSSize _labelSize;
	protected NSRect _tabRect;
	protected NSToolTipTag _tabToolTipTag;
	protected NSObject _auxiliaryStorage;

	public NSObject initWithIdentifier(NSObject identifier) { return null;
};
	public NSObject identifier() { return null;
};
	public NSObject view() { return null;
};
	public NSObject initialFirstResponder() { return null;
};
	public String label() { return null;
};
	public NSColor color() { return null;
};
	public NSTabState tabState() { return null;
};
	public NSTabView tabView() { return null;
};
	public void setIdentifier(NSObject identifier) { return ;
};
	public void setLabel(String label) { return ;
};
	public void setColor(NSColor color) { return ;
};
	public void setView(NSView view) { return ;
};
	public void setInitialFirstResponder(NSView view) { return ;
};
	public String toolTip() { return null;
};
	public void setToolTip(String toolTip) { return ;
};
	public void drawLabel(Boolean shouldTruncateLabel, NSRect labelRect) { return ;
};
	public NSSize sizeOfLabel(Boolean computeMin) { return null;
};
public static Integer NSSelectedTab = 0;
public static Integer NSBackgroundTab = 1;
public static Integer NSPressedTab = 2;

	public static class NSTabState extends NSUInteger { }}
