package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabViewItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTabView.*;

public abstract class INSTabView extends NSView {

	protected NSObject _tabViewItems;
	protected NSTabViewItem _selectedTabViewItem;
	protected NSFont _font;
	protected NSTabViewType _tabViewType;
	protected Boolean _allowTruncatedLabels;
	protected NSObject _delegate;
	protected Boolean _tabViewUnusedBOOL1;
	protected Boolean _drawsBackground;
	protected NSTabViewItem _pressedTabViewItem;
	protected Integer _endTabWidth;
	protected Integer _maxOverlap;
	protected Double _tabHeight;
	protected NSTabViewItem _tabViewItemWithKeyView;
	protected NSView _originalNextKeyView;


	protected NSTabViewItem _focusedTabViewItem;
	protected Void _tabViewUnused2;

	public void selectTabViewItem(NSTabViewItem tabViewItem) { return ;
};
	public void selectTabViewItemAtIndex(Integer index) { return ;
};
	public void selectTabViewItemWithIdentifier(NSObject identifier) { return ;
};
	public void takeSelectedTabViewItemFromSender(NSObject sender) { return ;
};
	public void selectFirstTabViewItem(NSObject sender) { return ;
};
	public void selectLastTabViewItem(NSObject sender) { return ;
};
	public void selectNextTabViewItem(NSObject sender) { return ;
};
	public void selectPreviousTabViewItem(NSObject sender) { return ;
};
	public NSTabViewItem selectedTabViewItem() { return null;
};
	public NSFont font() { return null;
};
	public NSTabViewType tabViewType() { return null;
};
	public NSArray tabViewItems() { return null;
};
	public Boolean allowsTruncatedLabels() { return null;
};
	public NSSize minimumSize() { return null;
};
	public Boolean drawsBackground() { return null;
};
	public NSControlTint controlTint() { return null;
};
	public NSControlSize controlSize() { return null;
};
	public void setFont(NSFont font) { return ;
};
	public void setTabViewType(NSTabViewType tabViewType) { return ;
};
	public void setAllowsTruncatedLabels(Boolean allowTruncatedLabels) { return ;
};
	public void setDrawsBackground(Boolean flag) { return ;
};
	public void setControlTint(NSControlTint controlTint) { return ;
};
	public void setControlSize(NSControlSize controlSize) { return ;
};
	public void addTabViewItem(NSTabViewItem tabViewItem) { return ;
};
	public void insertTabViewItem(NSTabViewItem tabViewItem, Integer index) { return ;
};
	public void removeTabViewItem(NSTabViewItem tabViewItem) { return ;
};
	public void setDelegate(NSObject anObject) { return ;
};
	public NSObject delegate() { return null;
};
	public NSTabViewItem tabViewItemAtPoint(NSPoint point) { return null;
};
	public NSRect contentRect() { return null;
};
	public Integer numberOfTabViewItems() { return null;
};
	public Integer indexOfTabViewItem(NSTabViewItem tabViewItem) { return null;
};
	public NSTabViewItem tabViewItemAtIndex(Integer index) { return null;
};
	public Integer indexOfTabViewItemWithIdentifier(NSObject identifier) { return null;
};
	public abstract class NSTabViewDelegate {
	
}
public static Integer NSTopTabsBezelBorder = 0;
public static Integer NSLeftTabsBezelBorder = 1;
public static Integer NSBottomTabsBezelBorder = 2;
public static Integer NSRightTabsBezelBorder = 3;
public static Integer NSNoTabsBezelBorder = 4;
public static Integer NSNoTabsLineBorder = 5;
public static Integer NSNoTabsNoBorder = 6;

	public static class NSTabViewType extends NSUInteger { }	public abstract class NSTabViewDelegate {
	public Boolean tabView(NSTabView tabView, NSTabViewItem tabViewItem) { return null;
};
	public void tabView(NSTabView tabView, NSTabViewItem tabViewItem) { return ;
};
	public void tabView(NSTabView tabView, NSTabViewItem tabViewItem) { return ;
};
	public void tabViewDidChangeNumberOfTabViewItems(NSTabView TabView) { return ;
};
	
}
}
