package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColor.*;

public abstract class INSTextStorageScripting {
	public NSArray attributeRuns() { return null;
};
	public void setAttributeRuns(NSArray attributeRuns) { return ;
};
	public NSArray paragraphs() { return null;
};
	public void setParagraphs(NSArray paragraphs) { return ;
};
	public NSArray words() { return null;
};
	public void setWords(NSArray words) { return ;
};
	public NSArray characters() { return null;
};
	public void setCharacters(NSArray characters) { return ;
};
	public NSFont font() { return null;
};
	public void setFont(NSFont font) { return ;
};
	public NSColor foregroundColor() { return null;
};
	public void setForegroundColor(NSColor color) { return ;
};
}
