package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbar.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;

public abstract class INSToolbarItem extends NSObject {

	protected NSToolbar _toolbar;
	protected NSImage _image;
	protected String _itemIdentifier;
	protected String _label;
	protected NSTextAlignment _labelAlignment;
	protected String _paletteLabel;
	protected String _toolTip;
	protected NSMenuItem _menuItemRep;
	protected Integer _tag;


	protected NSObject _tbiReserved;
	protected NSObject _itemViewer;
	protected NSView _view;
	protected NSSize _minSize;
	protected NSSize _maxSize;

	public NSObject initWithItemIdentifier(String itemIdentifier) { return null;
};
	public String itemIdentifier() { return null;
};
	public NSToolbar toolbar() { return null;
};
	public void setLabel(String label) { return ;
};
	public String label() { return null;
};
	public void setPaletteLabel(String paletteLabel) { return ;
};
	public String paletteLabel() { return null;
};
	public void setToolTip(String toolTip) { return ;
};
	public String toolTip() { return null;
};
	public void setMenuFormRepresentation(NSMenuItem menuItem) { return ;
};
	public NSMenuItem menuFormRepresentation() { return null;
};
	public void setTag(Integer tag) { return ;
};
	public Integer tag() { return null;
};
	public void setTarget(NSObject target) { return ;
};
	public NSObject target() { return null;
};
	public void setAction(SEL action) { return ;
};
	public SEL action() { return null;
};
	public void setEnabled(Boolean enabled) { return ;
};
	public Boolean isEnabled() { return null;
};
	public void setImage(NSImage image) { return ;
};
	public NSImage image() { return null;
};
	public void setView(NSView view) { return ;
};
	public NSView view() { return null;
};
	public void setMinSize(NSSize size) { return ;
};
	public NSSize minSize() { return null;
};
	public void setMaxSize(NSSize size) { return ;
};
	public NSSize maxSize() { return null;
};
	public void validate() { return ;
};
	public Boolean allowsDuplicatesInToolbar() { return null;
};
	public static String NSToolbarSeparatorItemIdentifier;
	public static String NSToolbarSpaceItemIdentifier;
	public static String NSToolbarFlexibleSpaceItemIdentifier;
	public static String NSToolbarShowColorsItemIdentifier;
	public static String NSToolbarShowFontsItemIdentifier;
	public static String NSToolbarCustomizeToolbarItemIdentifier;
	public static String NSToolbarPrintItemIdentifier;
public abstract static class INSObject {
	public Boolean validateToolbarItem(NSToolbarItem theItem) { return null;
};

}
}
