package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDocumentScripting.INSDocument.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;

public abstract class INSWindowController extends NSResponder {

	protected NSWindow _window;
	protected String _windowNibName;
	protected NSDocument _document;
	protected NSArray _topLevelObjects;
	protected NSObject _owner;


	protected String _frameAutosaveName;
	protected NSObject _moreVars;

	public NSObject initWithWindow(NSWindow window) { return null;
};
	public NSObject initWithWindowNibName(String windowNibName) { return null;
};
	public NSObject initWithWindowNibName(String windowNibName, NSObject owner) { return null;
};
	public NSObject initWithWindowNibPath(String windowNibPath, NSObject owner) { return null;
};
	public String windowNibName() { return null;
};
	public String windowNibPath() { return null;
};
	public NSObject owner() { return null;
};
	public void setWindowFrameAutosaveName(String name) { return ;
};
	public String windowFrameAutosaveName() { return null;
};
	public void setShouldCascadeWindows(Boolean flag) { return ;
};
	public Boolean shouldCascadeWindows() { return null;
};
	public NSObject document() { return null;
};
	public void setDocument(NSDocument document) { return ;
};
	public void setDocumentEdited(Boolean dirtyFlag) { return ;
};
	public void setShouldCloseDocument(Boolean flag) { return ;
};
	public Boolean shouldCloseDocument() { return null;
};
	public void setWindow(NSWindow window) { return ;
};
	public NSWindow window() { return null;
};
	public void synchronizeWindowTitleWithDocumentName() { return ;
};
	public String windowTitleForDocumentDisplayName(String displayName) { return null;
};
	public void close() { return ;
};
	public void showWindow(NSObject sender) { return ;
};
	public Boolean isWindowLoaded() { return null;
};
	public void windowWillLoad() { return ;
};
	public void windowDidLoad() { return ;
};
	public void loadWindow() { return ;
};
}
