package ru.andremoniy.jcocoa;

import ru.andremoniy.jcocoa.*;

public abstract class INSAttributedString extends NSObject {
	public String string() { return null;
};
	public NSDictionary attributesAtIndex(Integer location, NSRangePointer range) { return null;
};
	public Integer length() { return null;
};
	public NSObject attribute(String attrName, Integer location, NSRangePointer range) { return null;
};
	public NSAttributedString attributedSubstringFromRange(NSRange range) { return null;
};
	public NSDictionary attributesAtIndex(Integer location, NSRangePointer range, NSRange rangeLimit) { return null;
};
	public NSObject attribute(String attrName, Integer location, NSRangePointer range, NSRange rangeLimit) { return null;
};
	public Boolean isEqualToAttributedString(NSAttributedString other) { return null;
};
	public NSObject initWithString(String str) { return null;
};
	public NSObject initWithString(String str, NSDictionary attrs) { return null;
};
	public NSObject initWithAttributedString(NSAttributedString attrStr) { return null;
};
	public void replaceCharactersInRange(NSRange range, String str) { return ;
};
	public void setAttributes(NSDictionary attrs, NSRange range) { return ;
};
	public NSMutableString mutableString() { return null;
};
	public void addAttribute(String name, NSObject value, NSRange range) { return ;
};
	public void addAttributes(NSDictionary attrs, NSRange range) { return ;
};
	public void removeAttribute(String name, NSRange range) { return ;
};
	public void replaceCharactersInRange(NSRange range, NSAttributedString attrString) { return ;
};
	public void insertAttributedString(NSAttributedString attrString, Integer loc) { return ;
};
	public void appendAttributedString(NSAttributedString attrString) { return ;
};
	public void deleteCharactersInRange(NSRange range) { return ;
};
	public void setAttributedString(NSAttributedString attrString) { return ;
};
	public void beginEditing() { return ;
};
	public void endEditing() { return ;
};
}
