package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDistantObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDistantObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPortNameServer;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPortNameServer.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPort.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRunLoop;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRunLoop.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRunLoop;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRunLoop.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.INSDistantObjectRequest;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.INSDistantObjectRequest.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.INSDistantObjectRequest;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSConnection.INSDistantObjectRequest.*;

public abstract class INSConnection extends NSObject {

	protected NSObject receivePort;
	protected NSObject sendPort;
	protected NSObject delegate;
	protected int32_t busy;
	protected int32_t localProxyCount;
	protected int32_t waitCount;
	protected NSObject delayedRL;
	protected NSObject statistics;
	protected char isDead;
	protected char isValid;
	protected char wantsInvalid;
	protected char authGen;
	protected char authCheck;
	protected char encryptFlag;
	protected char decryptFlag;
	protected char doRequest;
	protected char isQueueing;
	protected char isMulti;
	protected char invalidateRP;
	protected NSObject ___1;
	protected NSObject ___2;
	protected NSObject runLoops;
	protected NSObject requestModes;
	protected NSObject rootObject;
	protected Void registerInfo;
	protected NSObject replMode;
	protected NSObject classInfoImported;
	protected NSObject releasedProxies;
	protected Void reserved;

	public NSDictionary statistics() { return null;
};
	public void setRequestTimeout(NSTimeInterval ti) { return ;
};
	public NSTimeInterval requestTimeout() { return null;
};
	public void setReplyTimeout(NSTimeInterval ti) { return ;
};
	public NSTimeInterval replyTimeout() { return null;
};
	public void setRootObject(NSObject anObject) { return ;
};
	public NSObject rootObject() { return null;
};
	public NSDistantObject rootProxy() { return null;
};
	public void setDelegate(NSObject anObject) { return ;
};
	public NSObject delegate() { return null;
};
	public void setIndependentConversationQueueing(Boolean yorn) { return ;
};
	public Boolean independentConversationQueueing() { return null;
};
	public Boolean isValid() { return null;
};
	public void invalidate() { return ;
};
	public void addRequestMode(String rmode) { return ;
};
	public void removeRequestMode(String rmode) { return ;
};
	public NSArray requestModes() { return null;
};
	public Boolean registerName(String name) { return null;
};
	public Boolean registerName(String name, NSPortNameServer server) { return null;
};
	public NSObject initWithReceivePort(NSPort receivePort, NSPort sendPort) { return null;
};
	public NSPort sendPort() { return null;
};
	public NSPort receivePort() { return null;
};
	public void enableMultipleThreads() { return ;
};
	public Boolean multipleThreadsEnabled() { return null;
};
	public void addRunLoop(NSRunLoop runloop) { return ;
};
	public void removeRunLoop(NSRunLoop runloop) { return ;
};
	public void runInNewThread() { return ;
};
	public NSArray remoteObjects() { return null;
};
	public NSArray localObjects() { return null;
};
	public abstract class NSConnectionDelegate {
	
}
	public static String NSConnectionReplyMode;
	public static String NSConnectionDidDieNotification;
	public abstract class NSConnectionDelegate {
	public Boolean makeNewConnection(NSConnection conn, NSConnection ancestor) { return null;
};
	public Boolean connection(NSConnection ancestor, NSConnection conn) { return null;
};
	public NSData authenticationDataForComponents(NSArray components) { return null;
};
	public Boolean authenticateComponents(NSArray components, NSData signature) { return null;
};
	public NSObject createConversationForConnection(NSConnection conn) { return null;
};
	public Boolean connection(NSConnection connection, NSDistantObjectRequest doreq) { return null;
};
	
}
	public static String NSFailedAuthenticationException;
	public static String NSConnectionDidInitializeNotification;
public abstract static class INSDistantObjectRequest extends NSObject {
	public NSInvocation invocation() { return null;
};
	public NSConnection connection() { return null;
};
	public NSObject conversation() { return null;
};
	public void replyWithException(NSException exception) { return ;
};

}
}
