package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURLHandle.*;

public abstract class INSURLHandle extends NSObject {

	protected NSMutableArray _clients;
	protected NSObject _data;
	protected NSURLHandleStatus _status;
	protected Integer _reserved;

	public NSURLHandleStatus status() { return null;
};
	public String failureReason() { return null;
};
	public void addClient(NSObject client) { return ;
};
	public void removeClient(NSObject client) { return ;
};
	public void loadInBackground() { return ;
};
	public void cancelLoadInBackground() { return ;
};
	public NSData resourceData() { return null;
};
	public NSData availableResourceData() { return null;
};
	public void flushCachedData() { return ;
};
	public void backgroundLoadDidFailWithReason(String reason) { return ;
};
	public void didLoadBytes(NSData newBytes, Boolean yorn) { return ;
};
	public  initWithURL(NSURL anURL, Boolean willCache) { return null;
};
	public NSObject propertyForKey(String propertyKey) { return null;
};
	public NSObject propertyForKeyIfAvailable(String propertyKey) { return null;
};
	public Boolean writeProperty(NSObject propertyValue, String propertyKey) { return null;
};
	public Boolean writeData(NSData data) { return null;
};
	public NSData loadInForeground() { return null;
};
	public void beginLoadInBackground() { return ;
};
	public void endLoadInBackground() { return ;
};
	public static String NSHTTPPropertyStatusCodeKey;
	public static String NSHTTPPropertyStatusReasonKey;
	public static String NSHTTPPropertyServerHTTPVersionKey;
	public static String NSHTTPPropertyRedirectionHeadersKey;
	public static String NSHTTPPropertyErrorPageDataKey;
public static Integer NSURLHandleNotLoaded = 0;
public static Integer NSURLHandleLoadSucceeded = null;
public static Integer NSURLHandleLoadInProgress = null;
public static Integer NSURLHandleLoadFailed = null;

	public static class NSURLHandleStatus extends NSUInteger { }	public abstract class NSURLHandleClient {
	public void URLHandle(NSURLHandle sender, NSData newBytes) { return ;
};
	public void URLHandleResourceDidBeginLoading(NSURLHandle sender) { return ;
};
	public void URLHandleResourceDidFinishLoading(NSURLHandle sender) { return ;
};
	public void URLHandleResourceDidCancelLoading(NSURLHandle sender) { return ;
};
	public void URLHandle(NSURLHandle sender, String reason) { return ;
};
	
}
}
