package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;

public abstract class INSUndoManager extends NSObject {

	protected NSObject _undoStack;
	protected NSObject _redoStack;
	protected NSArray _runLoopModes;
	protected Integer _disabled;


	protected NSObject _target;
	protected NSObject _proxy;
	protected Void _NSUndoManagerReserved1;
	protected Void _NSUndoManagerReserved2;

	public void beginUndoGrouping() { return ;
};
	public void endUndoGrouping() { return ;
};
	public Integer groupingLevel() { return null;
};
	public void disableUndoRegistration() { return ;
};
	public void enableUndoRegistration() { return ;
};
	public Boolean isUndoRegistrationEnabled() { return null;
};
	public Boolean groupsByEvent() { return null;
};
	public void setGroupsByEvent(Boolean groupsByEvent) { return ;
};
	public void setLevelsOfUndo(Integer levels) { return ;
};
	public Integer levelsOfUndo() { return null;
};
	public void setRunLoopModes(NSArray runLoopModes) { return ;
};
	public NSArray runLoopModes() { return null;
};
	public void undo() { return ;
};
	public void redo() { return ;
};
	public void undoNestedGroup() { return ;
};
	public Boolean canUndo() { return null;
};
	public Boolean canRedo() { return null;
};
	public Boolean isUndoing() { return null;
};
	public Boolean isRedoing() { return null;
};
	public void removeAllActions() { return ;
};
	public void removeAllActionsWithTarget(NSObject target) { return ;
};
	public void registerUndoWithTarget(NSObject target, SEL selector, NSObject anObject) { return ;
};
	public NSObject prepareWithInvocationTarget(NSObject target) { return null;
};
	public String undoActionName() { return null;
};
	public String redoActionName() { return null;
};
	public void setActionName(String actionName) { return ;
};
	public String undoMenuItemTitle() { return null;
};
	public String redoMenuItemTitle() { return null;
};
	public String undoMenuTitleForUndoActionName(String actionName) { return null;
};
	public String redoMenuTitleForUndoActionName(String actionName) { return null;
};
public static Integer NSUndoCloseGroupingRunLoopOrdering = 350000;
	public static String NSUndoManagerCheckpointNotification;
	public static String NSUndoManagerWillUndoChangeNotification;
	public static String NSUndoManagerWillRedoChangeNotification;
	public static String NSUndoManagerDidUndoChangeNotification;
	public static String NSUndoManagerDidRedoChangeNotification;
	public static String NSUndoManagerDidOpenUndoGroupNotification;
	public static String NSUndoManagerWillCloseUndoGroupNotification;
}
