package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSStringDrawing.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTextAttachment.INSAttributedString.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSAttributedString.*;

public abstract class INSAttributedString {
	public Integer length() { return null;
};
	public NSObject attribute(String attrName, Integer location, NSRangePointer range) { return null;
};
	public NSAttributedString attributedSubstringFromRange(NSRange range) { return null;
};
	public NSDictionary attributesAtIndex(Integer location, NSRangePointer range, NSRange rangeLimit) { return null;
};
	public NSObject attribute(String attrName, Integer location, NSRangePointer range, NSRange rangeLimit) { return null;
};
	public Boolean isEqualToAttributedString(NSAttributedString other) { return null;
};
	public NSObject initWithString(String str) { return null;
};
	public NSObject initWithString(String str, NSDictionary attrs) { return null;
};
	public NSObject initWithAttributedString(NSAttributedString attrStr) { return null;
};
public abstract static class INSMutableAttributedString extends NSAttributedString {
	public void replaceCharactersInRange(NSRange range, String str) { return ;
};
	public void setAttributes(NSDictionary attrs, NSRange range) { return ;
};

}
public abstract static class INSMutableAttributedString {
	public NSMutableString mutableString() { return null;
};
	public void addAttribute(String name, NSObject value, NSRange range) { return ;
};
	public void addAttributes(NSDictionary attrs, NSRange range) { return ;
};
	public void removeAttribute(String name, NSRange range) { return ;
};
	public void replaceCharactersInRange(NSRange range, NSAttributedString attrString) { return ;
};
	public void insertAttributedString(NSAttributedString attrString, Integer loc) { return ;
};
	public void appendAttributedString(NSAttributedString attrString) { return ;
};
	public void deleteCharactersInRange(NSRange range) { return ;
};
	public void setAttributedString(NSAttributedString attrString) { return ;
};
	public void beginEditing() { return ;
};
	public void endEditing() { return ;
};

}
}
