package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDirectoryEnumerator;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDirectoryEnumerator.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDirectoryEnumerator;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDirectoryEnumerator.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;

public abstract class INSFileManager extends NSObject {
	public NSArray mountedVolumeURLsIncludingResourceValuesForKeys(NSArray propertyKeys, NSVolumeEnumerationOptions options) { return null;
};
	public NSArray contentsOfDirectoryAtURL(NSURL url, NSArray keys, NSDirectoryEnumerationOptions mask, NSError error) { return null;
};
	public NSArray URLsForDirectory(NSSearchPathDirectory directory, NSSearchPathDomainMask domainMask) { return null;
};
	public NSURL URLForDirectory(NSSearchPathDirectory directory, NSSearchPathDomainMask domain, NSURL url, Boolean shouldCreate, NSError error) { return null;
};
	public Boolean copyItemAtURL(NSURL srcURL, NSURL dstURL, NSError error) { return null;
};
	public Boolean moveItemAtURL(NSURL srcURL, NSURL dstURL, NSError error) { return null;
};
	public Boolean linkItemAtURL(NSURL srcURL, NSURL dstURL, NSError error) { return null;
};
	public Boolean removeItemAtURL(NSURL URL, NSError error) { return null;
};
	public NSDictionary fileAttributesAtPath(String path, Boolean yorn) { return null;
};
	public Boolean changeFileAttributes(NSDictionary attributes, String path) { return null;
};
	public NSArray directoryContentsAtPath(String path) { return null;
};
	public NSDictionary fileSystemAttributesAtPath(String path) { return null;
};
	public String pathContentOfSymbolicLinkAtPath(String path) { return null;
};
	public Boolean createSymbolicLinkAtPath(String path, String otherpath) { return null;
};
	public Boolean createDirectoryAtPath(String path, NSDictionary attributes) { return null;
};
	public String currentDirectoryPath() { return null;
};
	public Boolean changeCurrentDirectoryPath(String path) { return null;
};
	public Boolean fileExistsAtPath(String path) { return null;
};
	public Boolean fileExistsAtPath(String path, Boolean isDirectory) { return null;
};
	public Boolean isReadableFileAtPath(String path) { return null;
};
	public Boolean isWritableFileAtPath(String path) { return null;
};
	public Boolean isExecutableFileAtPath(String path) { return null;
};
	public Boolean isDeletableFileAtPath(String path) { return null;
};
	public Boolean contentsEqualAtPath(String path1, String path2) { return null;
};
	public String displayNameAtPath(String path) { return null;
};
	public NSDirectoryEnumerator enumeratorAtPath(String path) { return null;
};
	public NSArray subpathsAtPath(String path) { return null;
};
	public NSData contentsAtPath(String path) { return null;
};
	public Boolean createFileAtPath(String path, NSData data, NSDictionary attr) { return null;
};
	public char fileSystemRepresentationWithPath(String path) { return null;
};
	public String stringWithFileSystemRepresentation(char str, Integer len) { return null;
};
	public Boolean replaceItemAtURL(NSURL originalItemURL, NSURL newItemURL, String backupItemName, NSFileManagerItemReplacementOptions options, NSURL resultingURL, NSError error) { return null;
};

	public static class NSVolumeEnumerationOptions extends NSUInteger { }
	public static class NSDirectoryEnumerationOptions extends NSUInteger { }
	public static class NSFileManagerItemReplacementOptions extends NSUInteger { }	public static String NSFileType;
	public static String NSFileTypeDirectory;
	public static String NSFileTypeRegular;
	public static String NSFileTypeSymbolicLink;
	public static String NSFileTypeSocket;
	public static String NSFileTypeCharacterSpecial;
	public static String NSFileTypeBlockSpecial;
	public static String NSFileTypeUnknown;
	public static String NSFileSize;
	public static String NSFileModificationDate;
	public static String NSFileReferenceCount;
	public static String NSFileDeviceIdentifier;
	public static String NSFileOwnerAccountName;
	public static String NSFileGroupOwnerAccountName;
	public static String NSFilePosixPermissions;
	public static String NSFileSystemNumber;
	public static String NSFileSystemFileNumber;
	public static String NSFileExtensionHidden;
	public static String NSFileHFSCreatorCode;
	public static String NSFileHFSTypeCode;
	public static String NSFileSystemSize;
	public static String NSFileSystemFreeSize;
	public static String NSFileSystemNodes;
	public static String NSFileSystemFreeNodes;
public abstract static class INSObject {
	public Boolean fileManager(NSFileManager fm, NSDictionary errorInfo) { return null;
};
	public void fileManager(NSFileManager fm, String path) { return ;
};

}
public abstract static class INSDirectoryEnumerator extends NSEnumerator {
	public NSDictionary fileAttributes() { return null;
};
	public NSDictionary directoryAttributes() { return null;
};
	public void skipDescendents() { return ;
};
	public Integer level() { return null;
};
	public void skipDescendants() { return ;
};

}
public abstract static class INSDictionary {
	public Long fileSize() { return null;
};
	public NSDate fileModificationDate() { return null;
};
	public String fileType() { return null;
};
	public Integer filePosixPermissions() { return null;
};
	public String fileOwnerAccountName() { return null;
};
	public String fileGroupOwnerAccountName() { return null;
};
	public Integer fileSystemNumber() { return null;
};
	public Integer fileSystemFileNumber() { return null;
};
	public Boolean fileExtensionHidden() { return null;
};
	public OSType fileHFSCreatorCode() { return null;
};
	public OSType fileHFSTypeCode() { return null;
};

}
}
