package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplication.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplication.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplicationScripting.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplicationScripting.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColorPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColorPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSavePanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSavePanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTableView.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTableView.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbarItem.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbarItem.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.framework.Versions.A.Headers.IPDEPluginInterface.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.framework.Versions.A.Headers.IPDEPluginInterface.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.framework.Versions.A.Headers.IPDEPluginInterface.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.framework.Versions.A.Headers.IPDEPluginInterface.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.framework.Versions.A.Headers.IPDEPluginInterface.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.framework.Versions.A.Headers.IPDEPluginInterface.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRBurnProgressPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRBurnProgressPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDREraseProgressPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDREraseProgressPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRSetupPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRSetupPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ExceptionHandling.Versions.A.Headers.INSExceptionHandler.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ExceptionHandling.Versions.A.Headers.INSExceptionHandler.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSClassDescription.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSClassDescription.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSObjectScripting.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSObjectScripting.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPortCoder.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPortCoder.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRunLoop.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRunLoop.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptKeyValueCoding.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptKeyValueCoding.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptWhoseTests.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptWhoseTests.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptWhoseTests.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptWhoseTests.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSThread.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSThread.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.InputMethodKit.Versions.A.Headers.IIMKInputController.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.InputMethodKit.Versions.A.Headers.IIMKInputController.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.QTKit.Versions.A.Headers.IQTMovie.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.QTKit.Versions.A.Headers.IQTMovie.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.QTKit.Versions.A.Headers.IQTMovieView.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.QTKit.Versions.A.Headers.IQTMovieView.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.ImageKit.framework.Versions.A.Headers.IImageKitDeprecated.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.ImageKit.framework.Versions.A.Headers.IImageKitDeprecated.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.PDFKit.framework.Versions.A.Headers.IPDFDocument.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.PDFKit.framework.Versions.A.Headers.IPDFDocument.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.PDFKit.framework.Versions.A.Headers.IPDFDocument.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.PDFKit.framework.Versions.A.Headers.IPDFDocument.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.PDFKit.framework.Versions.A.Headers.IPDFView.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.PDFKit.framework.Versions.A.Headers.IPDFView.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.QuartzFilters.framework.Versions.A.Headers.IQuartzFilterManager.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Quartz.Versions.A.Frameworks.QuartzFilters.framework.Versions.A.Headers.IQuartzFilterManager.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.SecurityInterface.Versions.A.Headers.ISFAuthorizationView.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.SecurityInterface.Versions.A.Headers.ISFAuthorizationView.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.SecurityInterface.Versions.A.Headers.ISFCertificatePanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.SecurityInterface.Versions.A.Headers.ISFCertificatePanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.SecurityInterface.Versions.A.Headers.ISFChooseIdentityPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.SecurityInterface.Versions.A.Headers.ISFChooseIdentityPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebDownload.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebDownload.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebEditingDelegate.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebEditingDelegate.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebFrameLoadDelegate.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebFrameLoadDelegate.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebJavaPlugIn.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebJavaPlugIn.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebPolicyDelegate.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebPolicyDelegate.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebResourceLoadDelegate.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebResourceLoadDelegate.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebUIDelegate.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.WebKit.Versions.A.Headers.IWebUIDelegate.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.XgridFoundation.Versions.A.Headers.IXGAuthenticator.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.XgridFoundation.Versions.A.Headers.IXGAuthenticator.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.XgridFoundation.Versions.A.Headers.IXGConnection.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.XgridFoundation.Versions.A.Headers.IXGConnection.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.XgridFoundation.Versions.A.Headers.IXGFileDownload.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.XgridFoundation.Versions.A.Headers.IXGFileDownload.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplication.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplication.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplicationScripting.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSApplicationScripting.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColorPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSColorPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDragging.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSavePanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSavePanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTableView.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSTableView.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbarItem.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSToolbarItem.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.Versions.A.Headers.IPDEPluginInterface.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.Versions.A.Headers.IPDEPluginInterface.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.Versions.A.Headers.IPDEPluginInterface.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.Versions.A.Headers.IPDEPluginInterface.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.Versions.A.Headers.IPDEPluginInterface.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ApplicationServices.Versions.A.Frameworks.PrintCore.Versions.A.Headers.IPDEPluginInterface.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRBurnProgressPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRBurnProgressPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDREraseProgressPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDREraseProgressPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRSetupPanel.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.DiscRecordingUI.Versions.A.Headers.IDRSetupPanel.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.ExceptionHandling.Versions.A.Headers.INSExceptionHandler.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.ExceptionHandling.Versions.A.Headers.INSExceptionHandler.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSClassDescription.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSClassDescription.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSObjectScripting.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSObjectScripting.INSObject.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPortCoder.INSObject;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPortCoder.INSObject.*;

public abstract class INSProtocolChecker {
	public NSObject initWithTarget(NSObject anObject, Protocol aProtocol) { return null;
};
}
