package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet.INSMutableSet;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet.INSMutableSet.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet.INSMutableSet;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet.INSMutableSet.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet.INSMutableSet;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet.INSMutableSet.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSArray.INSMutableArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSHelpManager.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSNibLoading.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSSound.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSBundle.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptClassDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSData.*;

public abstract class INSScriptSuiteRegistry extends NSObject {

	protected Boolean _isLoadingSDEFFiles;
	protected char _reserved1;
	protected NSMutableSet _seenBundles;
	protected NSMutableArray _suiteDescriptionsBeingCollected;
	protected NSScriptClassDescription _classDescriptionNeedingRegistration;
	protected NSMutableArray _suiteDescriptions;
	protected NSScriptCommandDescription _commandDescriptionNeedingRegistration;
	protected NSMutableDictionary _cachedClassDescriptionsByAppleEventCode;
	protected NSMutableDictionary _cachedCommandDescriptionsByAppleEventCodes;
	protected NSDictionary _cachedSuiteDescriptionsByName;
	protected NSMutableDictionary _complexTypeDescriptionsByName;
	protected NSMutableDictionary _listTypeDescriptionsByName;
	protected Integer _nextComplexTypeAppleEventCode;
	protected Void _reserved2;

	public void loadSuitesFromBundle(NSBundle bundle) { return ;
};
	public void loadSuiteWithDictionary(NSDictionary suiteDeclaration, NSBundle bundle) { return ;
};
	public void registerClassDescription(NSScriptClassDescription classDescription) { return ;
};
	public void registerCommandDescription(NSScriptCommandDescription commandDescription) { return ;
};
	public NSArray suiteNames() { return null;
};
	public FourCharCode appleEventCodeForSuite(String suiteName) { return null;
};
	public NSBundle bundleForSuite(String suiteName) { return null;
};
	public NSDictionary classDescriptionsInSuite(String suiteName) { return null;
};
	public NSDictionary commandDescriptionsInSuite(String suiteName) { return null;
};
	public String suiteForAppleEventCode(FourCharCode appleEventCode) { return null;
};
	public NSScriptClassDescription classDescriptionWithAppleEventCode(FourCharCode appleEventCode) { return null;
};
	public NSScriptCommandDescription commandDescriptionWithAppleEventClass(FourCharCode appleEventClassCode, FourCharCode appleEventIDCode) { return null;
};
	public NSData aeteResource(String languageName) { return null;
};
}
