package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSScriptObjectSpecifier;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSScriptObjectSpecifier.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSMutableDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptCommandDescription.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSScriptObjectSpecifier;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSScriptObjectSpecifier.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSScriptObjectSpecifier;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSScriptObjectSpecifiers.INSScriptObjectSpecifier.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;

public abstract class INSScriptCommand extends NSObject {

	protected NSScriptCommandDescription _commandDescription;
	protected NSObject _directParameter;
	protected NSScriptObjectSpecifier _receiversSpecifier;
	protected NSObject _evaluatedReceivers;
	protected NSDictionary _arguments;
	protected NSMutableDictionary _evaluatedArguments;


	protected NSObject _moreVars;
	protected Void _reserved;

	public NSObject initWithCommandDescription(NSScriptCommandDescription commandDef) { return null;
};
	public NSScriptCommandDescription commandDescription() { return null;
};
	public void setDirectParameter(NSObject directParameter) { return ;
};
	public NSObject directParameter() { return null;
};
	public void setReceiversSpecifier(NSScriptObjectSpecifier receiversRef) { return ;
};
	public NSScriptObjectSpecifier receiversSpecifier() { return null;
};
	public NSObject evaluatedReceivers() { return null;
};
	public void setArguments(NSDictionary args) { return ;
};
	public NSDictionary arguments() { return null;
};
	public NSDictionary evaluatedArguments() { return null;
};
	public Boolean isWellFormed() { return null;
};
	public NSObject performDefaultImplementation() { return null;
};
	public NSObject executeCommand() { return null;
};
	public void setScriptErrorNumber(Integer errorNumber) { return ;
};
	public void setScriptErrorString(String errorString) { return ;
};
	public Integer scriptErrorNumber() { return null;
};
	public String scriptErrorString() { return null;
};
public static Integer NSNoScriptError = 0;
public static Integer NSReceiverEvaluationScriptError = null;
public static Integer NSKeySpecifierEvaluationScriptError = null;
public static Integer NSArgumentEvaluationScriptError = null;
public static Integer NSReceiversCantHandleCommandScriptError = null;
public static Integer NSRequiredArgumentsMissingScriptError = null;
public static Integer NSArgumentsWrongScriptError = null;
public static Integer NSUnknownKeyScriptError = null;
public static Integer NSInternalScriptError = null;
public static Integer NSOperationNotSupportedForKeyScriptError = null;
public static Integer NSCannotCreateScriptCommandError = null;
}
