package ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;

public abstract class INSURL {
	public NSArray pathComponents() { return null;
};
	public String lastPathComponent() { return null;
};
	public String pathExtension() { return null;
};
	public NSURL URLByAppendingPathComponent(String pathComponent) { return null;
};
	public NSURL URLByDeletingLastPathComponent() { return null;
};
	public NSURL URLByAppendingPathExtension(String pathExtension) { return null;
};
	public NSURL URLByDeletingPathExtension() { return null;
};
	public NSURL URLByStandardizingPath() { return null;
};
	public NSURL URLByResolvingSymlinksInPath() { return null;
};

	public static class NSURLBookmarkCreationOptions extends NSUInteger { }
	public static class NSURLBookmarkResolutionOptions extends NSUInteger { }
	public static class NSURLBookmarkFileCreationOptions extends NSUInteger { }	public static String NSURLFileScheme;
	public static String NSURLNameKey;
	public static String NSURLLocalizedNameKey;
	public static String NSURLIsRegularFileKey;
	public static String NSURLIsDirectoryKey;
	public static String NSURLIsSymbolicLinkKey;
	public static String NSURLIsVolumeKey;
	public static String NSURLIsPackageKey;
	public static String NSURLIsSystemImmutableKey;
	public static String NSURLIsUserImmutableKey;
	public static String NSURLIsHiddenKey;
	public static String NSURLHasHiddenExtensionKey;
	public static String NSURLCreationDateKey;
	public static String NSURLContentAccessDateKey;
	public static String NSURLContentModificationDateKey;
	public static String NSURLAttributeModificationDateKey;
	public static String NSURLLinkCountKey;
	public static String NSURLParentDirectoryURLKey;
	public static String NSURLVolumeURLKey;
	public static String NSURLTypeIdentifierKey;
	public static String NSURLLocalizedTypeDescriptionKey;
	public static String NSURLLabelNumberKey;
	public static String NSURLLabelColorKey;
	public static String NSURLLocalizedLabelKey;
	public static String NSURLEffectiveIconKey;
	public static String NSURLCustomIconKey;
	public static String NSURLFileSizeKey;
	public static String NSURLFileAllocatedSizeKey;
	public static String NSURLIsAliasFileKey;
	public static String NSURLVolumeLocalizedFormatDescriptionKey;
	public static String NSURLVolumeTotalCapacityKey;
	public static String NSURLVolumeAvailableCapacityKey;
	public static String NSURLVolumeResourceCountKey;
	public static String NSURLVolumeSupportsPersistentIDsKey;
	public static String NSURLVolumeSupportsSymbolicLinksKey;
	public static String NSURLVolumeSupportsHardLinksKey;
	public static String NSURLVolumeSupportsJournalingKey;
	public static String NSURLVolumeIsJournalingKey;
	public static String NSURLVolumeSupportsSparseFilesKey;
	public static String NSURLVolumeSupportsZeroRunsKey;
	public static String NSURLVolumeSupportsCaseSensitiveNamesKey;
	public static String NSURLVolumeSupportsCasePreservedNamesKey;
public abstract static class INSString {
	public String stringByAddingPercentEscapesUsingEncoding(NSStringEncoding enc) { return null;
};
	public String stringByReplacingPercentEscapesUsingEncoding(NSStringEncoding enc) { return null;
};

}
}
