package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSScroller;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSScroller.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMatrix;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMatrix.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPasteboard.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSURL.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSImage.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSEvent.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSBrowser.*;

public abstract class INSBrowser {
	public void setAcceptsArrowKeys(Boolean flag) { return ;
};
	public Boolean acceptsArrowKeys() { return null;
};
	public void displayColumn(Integer column) { return ;
};
	public void displayAllColumns() { return ;
};
	public void scrollViaScroller(NSScroller sender) { return ;
};
	public void updateScroller() { return ;
};
	public abstract class NSBrowserDelegate {
	
}

	public static class __Brflags {
		Integer firstVisibleCalculationDisabled;
		Integer prefersAllColumnUserResizing;
		Integer usesSmallScrollers;
		Integer usesSmallSizeTitleFont;
		Integer actionNeedsToBeSent;
		Integer acceptsFirstMouse;
		Integer refusesFirstResponder;
		Integer disableCompositing;
		Integer delegateSelectsCellsByRow;
		Integer allowsIncrementalSearching;
		Integer time;
		Integer hasHorizontalScroller;
		Integer prohibitEmptySel;
		Integer sendActionOnArrowKeys;
		Integer dontDrawTitles;
		Integer acceptArrowKeys;
		Integer delegateValidatesColumns;
		Integer delegateDoesNotCreateRowsInMatrix;
		Integer delegateSelectsCellsByString;
		Integer delegateSetsTitles;
		Integer delegateImplementsWillDisplayCell;
		Integer separateColumns;
		Integer titleFromPrevious;
		Integer isTitled;
		Integer reuseColumns;
		Integer allowsBranchSelection;
		Integer allowsMultipleSelection;
	}

	public static class NSBrowserColumnResizingType extends NSUInteger { }
	public static class NSBrowserDropOperation extends NSUInteger { }	public static String NSBrowserColumnConfigurationDidChangeNotification;
	public abstract class NSBrowserDelegate {
	public Integer browser(NSBrowser sender, Integer column) { return null;
};
	public void browser(NSBrowser sender, Integer column, NSMatrix matrix) { return ;
};
	public Integer browser(NSBrowser browser, NSObject item) { return null;
};
	public NSObject browser(NSBrowser browser, Integer index, NSObject item) { return null;
};
	public Boolean browser(NSBrowser browser, NSObject item) { return null;
};
	public NSObject browser(NSBrowser browser, NSObject item) { return null;
};
	public Double browser(NSBrowser browser, Integer row, Integer columnIndex) { return null;
};
	public NSObject rootItemForBrowser(NSBrowser browser) { return null;
};
	public void browser(NSBrowser browser, NSObject object, NSObject item) { return ;
};
	public Boolean browser(NSBrowser browser, NSObject item) { return null;
};
	public void browser(NSBrowser sender, NSObject cell, Integer row, Integer column) { return ;
};
	public String browser(NSBrowser sender, Integer column) { return null;
};
	public Boolean browser(NSBrowser sender, String title, Integer column) { return null;
};
	public Boolean browser(NSBrowser sender, Integer row, Integer column) { return null;
};
	public Boolean browser(NSBrowser sender, Integer column) { return null;
};
	public void browserWillScroll(NSBrowser sender) { return ;
};
	public void browserDidScroll(NSBrowser sender) { return ;
};
	public Double browser(NSBrowser browser, Integer columnIndex, Boolean forUserResize, Double suggestedWidth) { return null;
};
	public Double browser(NSBrowser browser, Integer columnIndex) { return null;
};
	public void browserColumnConfigurationDidChange(NSNotification notification) { return ;
};
	public Boolean browser(NSBrowser browser, Integer row, Integer column) { return null;
};
	public Boolean browser(NSBrowser browser, NSIndexSet rowIndexes, Integer column, NSPasteboard pasteboard) { return null;
};
	public NSArray browser(NSBrowser browser, NSURL dropDestination, NSIndexSet rowIndexes, Integer column) { return null;
};
	public Boolean browser(NSBrowser browser, NSIndexSet rowIndexes, Integer column, NSEvent event) { return null;
};
	public NSImage browser(NSBrowser browser, NSIndexSet rowIndexes, Integer column, NSEvent event, NSPointPointer dragImageOffset) { return null;
};
	public NSDragOperation browser(NSBrowser browser, NSObject info, Integer row, Integer column, NSBrowserDropOperation dropOperation) { return null;
};
	public Boolean browser(NSBrowser browser, NSObject info, Integer row, Integer column, NSBrowserDropOperation dropOperation) { return null;
};
	public String browser(NSBrowser browser, Integer row, Integer column) { return null;
};
	public Boolean browser(NSBrowser browser, NSEvent event, String searchString) { return null;
};
	public Integer browser(NSBrowser browser, Integer startRow, Integer endRow, Integer column, String searchString) { return null;
};
	public NSViewController browser(NSBrowser browser, NSObject item) { return null;
};
	public NSViewController browser(NSBrowser browser, NSObject item) { return null;
};
	public void browser(NSBrowser browser, Integer oldLastColumn, Integer column) { return ;
};
	public NSIndexSet browser(NSBrowser browser, NSIndexSet proposedSelectionIndexes, Integer column) { return null;
};
	
}
}
