package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSLock;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSLock.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.*;

public abstract class INSDrawer extends NSResponder {

	protected NSDrawerState _drawerState;
	protected NSDrawerState _drawerNextState;
	protected NSRectEdge _drawerEdge;
	protected NSRectEdge _drawerNextEdge;
	protected NSRectEdge _drawerPreferredEdge;
	protected Double _drawerPercent;
	protected Double _drawerPercentSaved;
	protected Double _drawerLeadingOffset;
	protected Double _drawerTrailingOffset;
	protected NSLock _drawerLock;
	protected NSWindow _drawerWindow;
	protected NSWindow _drawerParentWindow;
	protected NSWindow _drawerNextParentWindow;
	protected String _drawerSaveName;
	protected CFAbsoluteTime _drawerStartTime;
	protected CFTimeInterval _drawerTotalTime;
	protected CFRunLoopRef _drawerLoop;
	protected CFRunLoopTimerRef _drawerTimer;
	protected NSObject _drawerDelegate;
	protected Integer _drawerFlags;
	protected CFRunLoopObserverRef _drawerObserver;

	public NSObject initWithContentSize(NSSize contentSize, NSRectEdge edge) { return null;
};
	public void setParentWindow(NSWindow parent) { return ;
};
	public NSWindow parentWindow() { return null;
};
	public void setContentView(NSView aView) { return ;
};
	public NSView contentView() { return null;
};
	public void setPreferredEdge(NSRectEdge edge) { return ;
};
	public NSRectEdge preferredEdge() { return null;
};
	public void setDelegate(NSObject anObject) { return ;
};
	public NSObject delegate() { return null;
};
	public void open() { return ;
};
	public void openOnEdge(NSRectEdge edge) { return ;
};
	public void close() { return ;
};
	public void open(NSObject sender) { return ;
};
	public void close(NSObject sender) { return ;
};
	public void toggle(NSObject sender) { return ;
};
	public Integer state() { return null;
};
	public NSRectEdge edge() { return null;
};
	public void setContentSize(NSSize size) { return ;
};
	public NSSize contentSize() { return null;
};
	public void setMinContentSize(NSSize size) { return ;
};
	public NSSize minContentSize() { return null;
};
	public void setMaxContentSize(NSSize size) { return ;
};
	public NSSize maxContentSize() { return null;
};
	public void setLeadingOffset(Double offset) { return ;
};
	public Double leadingOffset() { return null;
};
	public void setTrailingOffset(Double offset) { return ;
};
	public Double trailingOffset() { return null;
};
	public abstract class NSDrawerDelegate {
	
}
public static Integer NSDrawerClosedState = 0;
public static Integer NSDrawerOpeningState = 1;
public static Integer NSDrawerOpenState = 2;
public static Integer NSDrawerClosingState = 3;

	public static class NSDrawerState extends NSUInteger { }	public abstract class NSDrawerDelegate {
	public Boolean drawerShouldOpen(NSDrawer sender) { return null;
};
	public Boolean drawerShouldClose(NSDrawer sender) { return null;
};
	public NSSize drawerWillResizeContents(NSDrawer sender, NSSize contentSize) { return null;
};
	public void drawerWillOpen(NSNotification notification) { return ;
};
	public void drawerDidOpen(NSNotification notification) { return ;
};
	public void drawerWillClose(NSNotification notification) { return ;
};
	public void drawerDidClose(NSNotification notification) { return ;
};
	
}
	public static String NSDrawerWillOpenNotification;
	public static String NSDrawerDidOpenNotification;
	public static String NSDrawerWillCloseNotification;
	public static String NSDrawerDidCloseNotification;
public abstract static class INSWindow {
	public NSArray drawers() { return null;
};

}
}
