package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSGraphicsContext;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSGraphicsContext.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSWindowScripting.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSDrawer.INSWindow.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSGraphicsContext;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSGraphicsContext.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSSet;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSSet.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSSet.*;

public abstract class INSEvent extends NSObject {

	protected NSEventType _type;
	protected NSPoint _location;
	protected Integer _modifierFlags;
	protected NSObject _WSTimestamp;
	protected NSTimeInterval _timestamp;
	protected Integer _windowNumber;
	protected NSWindow _window;
	protected NSGraphicsContext _context;


	protected Void _eventRef;

	public NSEventType type() { return null;
};
	public Integer modifierFlags() { return null;
};
	public NSTimeInterval timestamp() { return null;
};
	public NSWindow window() { return null;
};
	public Integer windowNumber() { return null;
};
	public NSGraphicsContext context() { return null;
};
	public Integer clickCount() { return null;
};
	public Integer buttonNumber() { return null;
};
	public Integer eventNumber() { return null;
};
	public Double pressure() { return null;
};
	public NSPoint locationInWindow() { return null;
};
	public Double deltaX() { return null;
};
	public Double deltaY() { return null;
};
	public Double deltaZ() { return null;
};
	public String characters() { return null;
};
	public String charactersIgnoringModifiers() { return null;
};
	public Boolean isARepeat() { return null;
};
	public Short keyCode() { return null;
};
	public Integer trackingNumber() { return null;
};
	public void userData() { return ;
};
	public Short subtype() { return null;
};
	public Integer data1() { return null;
};
	public Integer data2() { return null;
};
	public Double magnification() { return null;
};
	public NSSet touchesMatchingPhase(NSTouchPhase phase, NSView view) { return null;
};
public static Integer NSLeftMouseDown = 1;
public static Integer NSLeftMouseUp = 2;
public static Integer NSRightMouseDown = 3;
public static Integer NSRightMouseUp = 4;
public static Integer NSMouseMoved = 5;
public static Integer NSLeftMouseDragged = 6;
public static Integer NSRightMouseDragged = 7;
public static Integer NSMouseEntered = 8;
public static Integer NSMouseExited = 9;
public static Integer NSKeyDown = 10;
public static Integer NSKeyUp = 11;
public static Integer NSFlagsChanged = 12;
public static Integer NSAppKitDefined = 13;
public static Integer NSSystemDefined = 14;
public static Integer NSApplicationDefined = 15;
public static Integer NSPeriodic = 16;
public static Integer NSCursorUpdate = 17;
public static Integer NSScrollWheel = 22;
public static Integer NSOtherMouseDown = 25;
public static Integer NSOtherMouseUp = 26;
public static Integer NSOtherMouseDragged = 27;

	public static class NSEventType extends NSUInteger { }public static Integer NSLeftMouseDownMask = 1;
public static Integer NSLeftMouseUpMask = 1;
public static Integer NSRightMouseDownMask = 1;
public static Integer NSRightMouseUpMask = 1;
public static Integer NSMouseMovedMask = 1;
public static Integer NSLeftMouseDraggedMask = 1;
public static Integer NSRightMouseDraggedMask = 1;
public static Integer NSMouseEnteredMask = 1;
public static Integer NSMouseExitedMask = 1;
public static Integer NSKeyDownMask = 1;
public static Integer NSKeyUpMask = 1;
public static Integer NSFlagsChangedMask = 1;
public static Integer NSAppKitDefinedMask = 1;
public static Integer NSSystemDefinedMask = 1;
public static Integer NSApplicationDefinedMask = 1;
public static Integer NSPeriodicMask = 1;
public static Integer NSCursorUpdateMask = 1;
public static Integer NSScrollWheelMask = 1;
public static Integer NSOtherMouseDownMask = 1;
public static Integer NSOtherMouseUpMask = 1;
public static Integer NSOtherMouseDraggedMask = 1;
public static Integer NSAnyEventMask = 0;
public static Integer NSAlphaShiftKeyMask = 1;
public static Integer NSShiftKeyMask = 1;
public static Integer NSControlKeyMask = 1;
public static Integer NSAlternateKeyMask = 1;
public static Integer NSCommandKeyMask = 1;
public static Integer NSNumericPadKeyMask = 1;
public static Integer NSHelpKeyMask = 1;
public static Integer NSFunctionKeyMask = 1;
public static Integer NSUpArrowFunctionKey = 0xF700;
public static Integer NSDownArrowFunctionKey = 0xF701;
public static Integer NSLeftArrowFunctionKey = 0xF702;
public static Integer NSRightArrowFunctionKey = 0xF703;
public static Integer NSF1FunctionKey = 0xF704;
public static Integer NSF2FunctionKey = 0xF705;
public static Integer NSF3FunctionKey = 0xF706;
public static Integer NSF4FunctionKey = 0xF707;
public static Integer NSF5FunctionKey = 0xF708;
public static Integer NSF6FunctionKey = 0xF709;
public static Integer NSF7FunctionKey = 0xF70A;
public static Integer NSF8FunctionKey = 0xF70B;
public static Integer NSF9FunctionKey = 0xF70C;
public static Integer NSF10FunctionKey = 0xF70D;
public static Integer NSF11FunctionKey = 0xF70E;
public static Integer NSF12FunctionKey = 0xF70F;
public static Integer NSF13FunctionKey = 0xF710;
public static Integer NSF14FunctionKey = 0xF711;
public static Integer NSF15FunctionKey = 0xF712;
public static Integer NSF16FunctionKey = 0xF713;
public static Integer NSF17FunctionKey = 0xF714;
public static Integer NSF18FunctionKey = 0xF715;
public static Integer NSF19FunctionKey = 0xF716;
public static Integer NSF20FunctionKey = 0xF717;
public static Integer NSF21FunctionKey = 0xF718;
public static Integer NSF22FunctionKey = 0xF719;
public static Integer NSF23FunctionKey = 0xF71A;
public static Integer NSF24FunctionKey = 0xF71B;
public static Integer NSF25FunctionKey = 0xF71C;
public static Integer NSF26FunctionKey = 0xF71D;
public static Integer NSF27FunctionKey = 0xF71E;
public static Integer NSF28FunctionKey = 0xF71F;
public static Integer NSF29FunctionKey = 0xF720;
public static Integer NSF30FunctionKey = 0xF721;
public static Integer NSF31FunctionKey = 0xF722;
public static Integer NSF32FunctionKey = 0xF723;
public static Integer NSF33FunctionKey = 0xF724;
public static Integer NSF34FunctionKey = 0xF725;
public static Integer NSF35FunctionKey = 0xF726;
public static Integer NSInsertFunctionKey = 0xF727;
public static Integer NSDeleteFunctionKey = 0xF728;
public static Integer NSHomeFunctionKey = 0xF729;
public static Integer NSBeginFunctionKey = 0xF72A;
public static Integer NSEndFunctionKey = 0xF72B;
public static Integer NSPageUpFunctionKey = 0xF72C;
public static Integer NSPageDownFunctionKey = 0xF72D;
public static Integer NSPrintScreenFunctionKey = 0xF72E;
public static Integer NSScrollLockFunctionKey = 0xF72F;
public static Integer NSPauseFunctionKey = 0xF730;
public static Integer NSSysReqFunctionKey = 0xF731;
public static Integer NSBreakFunctionKey = 0xF732;
public static Integer NSResetFunctionKey = 0xF733;
public static Integer NSStopFunctionKey = 0xF734;
public static Integer NSMenuFunctionKey = 0xF735;
public static Integer NSUserFunctionKey = 0xF736;
public static Integer NSSystemFunctionKey = 0xF737;
public static Integer NSPrintFunctionKey = 0xF738;
public static Integer NSClearLineFunctionKey = 0xF739;
public static Integer NSClearDisplayFunctionKey = 0xF73A;
public static Integer NSInsertLineFunctionKey = 0xF73B;
public static Integer NSDeleteLineFunctionKey = 0xF73C;
public static Integer NSInsertCharFunctionKey = 0xF73D;
public static Integer NSDeleteCharFunctionKey = 0xF73E;
public static Integer NSPrevFunctionKey = 0xF73F;
public static Integer NSNextFunctionKey = 0xF740;
public static Integer NSSelectFunctionKey = 0xF741;
public static Integer NSExecuteFunctionKey = 0xF742;
public static Integer NSUndoFunctionKey = 0xF743;
public static Integer NSRedoFunctionKey = 0xF744;
public static Integer NSFindFunctionKey = 0xF745;
public static Integer NSHelpFunctionKey = 0xF746;
public static Integer NSModeSwitchFunctionKey = 0xF747;
public static Integer NSWindowExposedEventType = 0;
public static Integer NSApplicationActivatedEventType = 1;
public static Integer NSApplicationDeactivatedEventType = 2;
public static Integer NSWindowMovedEventType = 4;
public static Integer NSScreenChangedEventType = 8;
public static Integer NSAWTEventType = 16;
public static Integer NSPowerOffEventType = 1;
}
