package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFontManager.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSFont.*;

public abstract class INSFontPanel extends NSPanel {

	protected NSFontManager _manager;
	protected NSArray _collectionNames;
	protected NSObject _selection;
	protected Void _carbonNotification;
	protected NSObject _targetObject;
	protected NSObject _familyList;
	protected NSObject _faceList;
	protected NSObject _sizeList;
	protected NSObject _mainCollectionList;
	protected NSObject _sizeField;
	protected NSObject _sizeSlider;
	protected NSObject _sizeSliderBox;
	protected NSObject _preview;
	protected NSObject _previewCaption;
	protected NSObject _mainSplitView;
	protected NSObject _mmCollectionList;
	protected NSObject _mmFamilyList;
	protected NSObject _mmFaceList;
	protected NSObject _mmSizeList;
	protected NSObject _extrasPopup;
	protected NSObject _searchField;
	protected NSObject _fixedListButton;
	protected NSObject _sliderButton;
	protected NSObject _accessoryView;


	protected NSObject _regularModeBox;
	protected NSObject _miniModeBox;
	protected NSObject _modeBoxSuperview;
	protected NSObject _collectionLabel;
	protected NSObject _sizeLabel;
	protected NSObject _faceLabel;
	protected NSObject _familyLabel;
	protected NSObject _sizeStyleButton;
	protected NSObject _newSizeField;
	protected NSObject _editSizeList;
	protected NSObject _editSizeListBox;
	protected NSObject _editSizeSliderBox;
	protected NSObject _editSizeSliderMaxField;
	protected NSObject _editSizeSliderMinField;
	protected NSObject _sizeEditWindow;
	protected NSObject _availableSizes;
	protected NSObject _addCollectionButton;
	protected NSObject _removeCollectionButton;
	protected Double _fontPanelPreviewHeight;
	protected NSObject _typographyPanel;
	protected NSObject _actionButton;
	protected NSObject _fontEffectsBox;
	protected Integer _sizeStyle;

	public NSView accessoryView() { return null;
};
	public void setAccessoryView(NSView aView) { return ;
};
	public void setPanelFont(NSFont fontObj, Boolean flag) { return ;
};
	public NSFont panelConvertFont(NSFont fontObj) { return null;
};
	public Boolean worksWhenModal() { return null;
};
	public Boolean isEnabled() { return null;
};
	public void setEnabled(Boolean flag) { return ;
};
	public void reloadDefaultFontFamilies() { return ;
};
public static Integer NSFPPreviewButton = 131;
public static Integer NSFPRevertButton = 130;
public static Integer NSFPSetButton = 132;
public static Integer NSFPPreviewField = 128;
public static Integer NSFPSizeField = 129;
public static Integer NSFPSizeTitle = 133;
public static Integer NSFPCurrentField = 134;
}
