package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenu.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSMenuItem.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;

public abstract class INSPopUpButtonCell extends NSMenuItemCell {

	protected NSMenu _menu;
	protected Integer _selectedIndex;

	public NSObject initTextCell(String stringValue, Boolean pullDown) { return null;
};
	public void setMenu(NSMenu menu) { return ;
};
	public NSMenu menu() { return null;
};
	public void setPullsDown(Boolean flag) { return ;
};
	public Boolean pullsDown() { return null;
};
	public void setAutoenablesItems(Boolean flag) { return ;
};
	public Boolean autoenablesItems() { return null;
};
	public void setPreferredEdge(NSRectEdge edge) { return ;
};
	public NSRectEdge preferredEdge() { return null;
};
	public void setUsesItemFromMenu(Boolean flag) { return ;
};
	public Boolean usesItemFromMenu() { return null;
};
	public void setAltersStateOfSelectedItem(Boolean flag) { return ;
};
	public Boolean altersStateOfSelectedItem() { return null;
};
	public void addItemWithTitle(String title) { return ;
};
	public void addItemsWithTitles(NSArray itemTitles) { return ;
};
	public void insertItemWithTitle(String title, Integer index) { return ;
};
	public void removeItemWithTitle(String title) { return ;
};
	public void removeItemAtIndex(Integer index) { return ;
};
	public void removeAllItems() { return ;
};
	public NSArray itemArray() { return null;
};
	public Integer numberOfItems() { return null;
};
	public Integer indexOfItem(NSMenuItem item) { return null;
};
	public Integer indexOfItemWithTitle(String title) { return null;
};
	public Integer indexOfItemWithTag(Integer tag) { return null;
};
	public Integer indexOfItemWithRepresentedObject(NSObject obj) { return null;
};
	public Integer indexOfItemWithTarget(NSObject target, SEL actionSelector) { return null;
};
	public NSMenuItem itemAtIndex(Integer index) { return null;
};
	public NSMenuItem itemWithTitle(String title) { return null;
};
	public NSMenuItem lastItem() { return null;
};
	public void selectItem(NSMenuItem item) { return ;
};
	public void selectItemAtIndex(Integer index) { return ;
};
	public void selectItemWithTitle(String title) { return ;
};
	public void setTitle(String aString) { return ;
};
	public NSMenuItem selectedItem() { return null;
};
	public Integer indexOfSelectedItem() { return null;
};
	public void synchronizeTitleAndSelectedItem() { return ;
};
	public String itemTitleAtIndex(Integer index) { return null;
};
	public NSArray itemTitles() { return null;
};
	public String titleOfSelectedItem() { return null;
};
	public void attachPopUpWithFrame(NSRect cellFrame, NSView controlView) { return ;
};
	public void dismissPopUp() { return ;
};
	public void performClickWithFrame(NSRect frame, NSView controlView) { return ;
};
	public NSPopUpArrowPosition arrowPosition() { return null;
};
	public void setArrowPosition(NSPopUpArrowPosition position) { return ;
};
	public NSObject objectValue() { return null;
};
	public void setObjectValue(NSObject obj) { return ;
};
public static Integer NSPopUpNoArrow = 0;
public static Integer NSPopUpArrowAtCenter = 1;
public static Integer NSPopUpArrowAtBottom = 2;

	public static class NSPopUpArrowPosition extends NSUInteger { }	public static String NSPopUpButtonCellWillPopUpNotification;
}
