package ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers;

import ru.andremoniy.jcocoa.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSFileManager.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSDictionary.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSClipView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSRulerView.INSView.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel.*;
import ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel;
import static ru.andremoniy.jcocoa.Frameworks.AppKit.Versions.C.Headers.INSPanel.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSRange.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSKeyValueCoding.INSArray.*;
import ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray;
import static ru.andremoniy.jcocoa.Frameworks.Foundation.Versions.C.Headers.INSPathUtilities.INSArray.*;

public abstract class INSSpellChecker extends NSObject {

	protected NSObject _guessesBrowser;
	protected NSObject _wordField;
	protected NSObject _languagePopUp;
	protected NSObject _reserved1;
	protected NSObject _panel;
	protected NSObject _reserved2;
	protected NSObject _correctButton;
	protected NSObject _guessButton;
	protected NSObject _ignoreButton;
	protected NSObject _reserved3;
	protected NSObject _languagesBrowser;
	protected NSObject _quotesBrowser;
	protected NSObject _replacementsBrowser;
	protected NSObject _defineButton;


	protected NSObject _substitutionsPanel;
	protected NSObject _reserved4;
	protected NSObject _learnButton;
	protected NSObject _infoField;
	protected NSObject _grammarControl;

	public NSRange checkSpellingOfString(String stringToCheck, Integer startingOffset, String language, Boolean wrapFlag, Integer tag, Integer wordCount) { return null;
};
	public NSRange checkSpellingOfString(String stringToCheck, Integer startingOffset) { return null;
};
	public Integer countWordsInString(String stringToCount, String language) { return null;
};
	public NSRange checkGrammarOfString(String stringToCheck, Integer startingOffset, String language, Boolean wrapFlag, Integer tag, NSArray details) { return null;
};
	public static String NSTextCheckingOrthographyKey;
	public static String NSTextCheckingQuotesKey;
	public static String NSTextCheckingReplacementsKey;
	public static String NSTextCheckingReferenceDateKey;
	public static String NSTextCheckingReferenceTimeZoneKey;
	public static String NSTextCheckingDocumentURLKey;
	public static String NSTextCheckingDocumentTitleKey;
	public static String NSTextCheckingDocumentAuthorKey;
	public NSArray userQuotesArrayForLanguage(String language) { return null;
};
	public NSDictionary userReplacementsDictionary() { return null;
};
	public void updateSpellingPanelWithMisspelledWord(String word) { return ;
};
	public void updateSpellingPanelWithGrammarString(String string, NSDictionary detail) { return ;
};
	public NSPanel spellingPanel() { return null;
};
	public NSView accessoryView() { return null;
};
	public void setAccessoryView(NSView aView) { return ;
};
	public NSPanel substitutionsPanel() { return null;
};
	public NSViewController substitutionsPanelAccessoryViewController() { return null;
};
	public void setSubstitutionsPanelAccessoryViewController(NSViewController accessoryController) { return ;
};
	public void updatePanels() { return ;
};
	public void ignoreWord(String wordToIgnore, Integer tag) { return ;
};
	public NSArray ignoredWordsInSpellDocumentWithTag(Integer tag) { return null;
};
	public void setIgnoredWords(NSArray words, Integer tag) { return ;
};
	public NSArray guessesForWordRange(NSRange range, String string, String language, Integer tag) { return null;
};
	public NSArray completionsForPartialWordRange(NSRange range, String string, String language, Integer tag) { return null;
};
	public void closeSpellDocumentWithTag(Integer tag) { return ;
};
	public NSArray availableLanguages() { return null;
};
	public NSArray userPreferredLanguages() { return null;
};
	public Boolean automaticallyIdentifiesLanguages() { return null;
};
	public void setAutomaticallyIdentifiesLanguages(Boolean flag) { return ;
};
	public String language() { return null;
};
	public Boolean setLanguage(String language) { return null;
};
	public void setWordFieldStringValue(String aString) { return ;
};
	public void learnWord(String word) { return ;
};
	public Boolean hasLearnedWord(String word) { return null;
};
	public void unlearnWord(String word) { return ;
};
}
